name: example
description: Simple project to showcase the usage of flame_tiled

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flame: 1.23.0
  flame_tiled:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/map.tmx
    - assets/images/map-level1.png
    - assets/images/map-level2.png
    - assets/images/coins.png
dev_dependencies:
  flutter_lints: ^5.0.0
